# Generated by Django 5.2.16 on 2026-07-20 13:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BOQ", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="management_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="e.g. 10.00 for 10%",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vat_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Applied to the management fee only, per her sample BoQ",
                max_digits=5,
            ),
        ),
    ]
