# Generated by Django 5.2.16 on 2026-07-20 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("staff", "Staff"),
                            ("branch_manager", "Branch Manager"),
                            ("bloc_manager", "Bloc Manager"),
                            ("hod", "Head of Department"),
                            ("coo", "COO"),
                            ("finance", "Finance"),
                            ("admin", "System Admin"),
                        ],
                        default="staff",
                        max_length=32,
                    ),
                ),
                ("branch", models.CharField(blank=True, max_length=100)),
                ("is_coo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
