# Generated by Django 5.2.16 on 2026-07-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogitem",
            options={"ordering": ["trade__order", "id"]},
        ),
    ]
